"""Identity middleware — ASGI middleware for identity resolution.

The middleware runs on every HTTP request BEFORE route handlers. It:

1.  Passes the ``Request`` to the configured ``IdentityProvider``.
2.  Attaches the resulting ``UserPrincipal`` to ``request.state.principal``.
3.  Resolves workspace/tenant context and stores it in ``request.state.context``.
4.  Injects ``X-Request-ID`` (generated by ``app/main.py``).
"""

from __future__ import annotations

from typing import Any

from app.modules.identity.models import UserPrincipal
from app.modules.identity.provider import create_identity_provider


class IdentityMiddleware:
    """ASGI middleware — resolves identity on every request."""

    def __init__(self, app: Any) -> None:
        self.app = app
        self._provider = create_identity_provider()

    async def __call__(self, scope: Any, receive: Any, send: Any) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        # Build a request-like object from the ASGI scope
        # We cannot use the FastAPI Request here because the middleware
        # runs before FastAPI creates it. Instead we store the principal
        # on the scope state for FastAPI dependencies to pick up.
        scope["state"] = scope.get("state", {})
        scope["state"]["identity_principal"] = await self._resolve_from_scope(scope)

        # Also store workspace context from query string or path
        ws_id = _extract_workspace_from_scope(scope)
        scope["state"]["identity_workspace_id"] = ws_id

        await self.app(scope, receive, send)

    async def _resolve_from_scope(self, scope: Any) -> UserPrincipal:
        """Resolve identity from ASGI scope headers."""
        from starlette.datastructures import MutableHeaders

        headers_list: list[tuple[bytes, bytes]] = scope.get("headers", []) or []
        if isinstance(headers_list, list):
            scope_headers = {
                k.decode("latin-1"): v.decode("latin-1")
                for k, v in headers_list
                if isinstance(k, (bytes, bytearray)) and isinstance(v, (bytes, bytearray))
            }
        else:
            scope_headers = {}

        # Build a minimal request skeleton for the provider
        class _ScopeRequest:
            def __init__(self, headers_dict: dict[str, str]) -> None:
                self.headers = MutableHeaders()
                for k, v in headers_dict.items():
                    self.headers[k] = v

        req = _ScopeRequest(scope_headers)
        return await self._provider.resolve(req)


class MutableMapping:
    def __init__(self, data: dict[str, str]) -> None:
        self._data = dict(data)

    def __getitem__(self, key: str) -> str:
        return self._data.get(key.lower(), "")

    def __setitem__(self, key: str, value: str) -> None:
        self._data[key] = value

    def get(self, key: str, default: str = "") -> str:
        return self._data.get(key.lower(), default)

    def items(self) -> list[tuple[str, str]]:
        return list(self._data.items())


def _extract_workspace_from_scope(scope: Any) -> str:
    query: bytes = scope.get("query_string", b"")
    if isinstance(query, bytes):
        query_str = query.decode("latin-1", errors="ignore")
    elif isinstance(query, str):
        query_str = query
    else:
        query_str = ""
    for pair in query_str.split("&"):
        if "=" not in pair:
            continue
        key, value = pair.split("=", 1)
        if key == "workspace_id" and value:
            return value
    return ""
