"""Nexus bounded RL — candidate action generation.

This is NOT an autonomous executor. The RL layer proposes candidate
actions; every candidate MUST:

  1. Be simulated in the Digital Twin
  2. Be compared against deterministic KPIs
  3. Pass policy checks
  4. Receive human approval

Before any execution.

The architecture enforces this at every level: there is no code path
from the RL generator to execution. It writes only to a candidate list
that the Decision Engine reads.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any
from uuid import uuid4


def _utc_now() -> datetime:
    return datetime.now(UTC)


CANDIDATE_ACTION_TYPES = [
    "expedite_air_freight",
    "shift_to_alternate_supplier",
    "reroute_via_alternate_port",
    "split_order_across_suppliers",
    "hold_order_consolidate",
    "increase_safety_stock",
    "negotiate_priority_fulfillment",
    "partial_shipment_accept",
    "delay_promotion",
    "reallocate_inventory",
]


@dataclass
class CandidateAction:
    """One candidate action generated by the RL policy."""

    candidate_id: str
    action_type: str
    target_entity_id: str
    parameters: dict[str, Any] = field(default_factory=dict)
    predicted_nev: float = 0.0  # Net Economic Value estimate
    predicted_sla_pct: float = 0.0  # Probability of meeting SLA
    predicted_cost: float = 0.0  # Implementation cost
    predicted_delay_reduction_days: float = 0.0
    confidence: float = 0.5
    policy_safe: bool = True  # Pre-flight policy check
    gnn_support_score: float = 0.0  # Whether GNN features support this
    source: str = "rl"  # rl|heuristic|gnn|human
    explanation: str = ""
    created_at: datetime = field(default_factory=_utc_now)

    def to_dict(self) -> dict[str, Any]:
        return {
            "candidate_id": self.candidate_id,
            "action_type": self.action_type,
            "target_entity_id": self.target_entity_id,
            "parameters": self.parameters,
            "predicted_nev": round(self.predicted_nev, 2),
            "predicted_sla_pct": round(self.predicted_sla_pct, 4),
            "predicted_cost": round(self.predicted_cost, 2),
            "predicted_delay_reduction_days": round(self.predicted_delay_reduction_days, 1),
            "confidence": round(self.confidence, 4),
            "policy_safe": self.policy_safe,
            "gnn_support_score": round(self.gnn_support_score, 4),
            "source": self.source,
            "explanation": self.explanation,
            "created_at": self.created_at.isoformat(),
            "bounded": True,  # Always True — RL never executes directly
            "requires_simulation": True,
            "requires_human_approval": True,
        }


class CandidateGenerator:
    """Deterministic heuristic + RL-style candidate generator.

    In a production system this calls a trained policy network. Here we
    implement a rule-based policy that produces diverse, sensible
    candidates for the given situation. The interface is identical —
    a trained model can be swapped in behind `generate_candidates()`.
    """

    MAX_CANDIDATES_PER_DECISION = 5
    COST_WEIGHT = 0.3
    SLA_WEIGHT = 0.5
    NEV_WEIGHT = 0.2

    def generate_candidates(
        self,
        *,
        situation: dict[str, Any],
        risk_score: float = 0.5,
        entity_id: str,
        entity_kind: str,
        gnn_features: dict[str, Any] | None = None,
        similar_suppliers: list[dict[str, Any]] | None = None,
        blast_radius_count: int = 0,
        revenue_exposure: float = 0.0,
        current_delay_days: float = 0.0,
    ) -> list[CandidateAction]:
        """Generate bounded candidate actions for a risk/situation.

        NEVER returns more than MAX_CANDIDATES_PER_DECISION. Every
        candidate is marked as requiring simulation + human approval.
        """
        candidates: list[CandidateAction] = []
        gnn_features = gnn_features or {}
        similar_suppliers = similar_suppliers or []

        if "supplier" in entity_kind.lower() or risk_score > 0.6:
            # Supplier risk: consider alternate sourcing
            if similar_suppliers:
                top_alt = max(similar_suppliers, key=lambda s: s.get("similarity_score", 0))
                shift_pct = min(0.6, top_alt.get("can_absorb_pct", 0.3))
                candidates.append(
                    self._make_candidate(
                        action_type="shift_to_alternate_supplier",
                        target_entity_id=entity_id,
                        parameters={
                            "alternate_supplier_id": top_alt["supplier_id"],
                            "shift_percentage": round(shift_pct, 2),
                            "similarity_score": top_alt.get("similarity_score", 0),
                        },
                        predicted_nev=revenue_exposure * shift_pct * 0.7 - revenue_exposure * 0.05,
                        predicted_sla_pct=min(0.92, 0.5 + shift_pct * 0.4),
                        predicted_cost=revenue_exposure * 0.08,
                        delay_reduction=current_delay_days * 0.5,
                        confidence=0.6 + top_alt.get("similarity_score", 0) * 0.2,
                        explanation=f"Shift {int(shift_pct * 100)}% of volume to {top_alt['supplier_id']} (similarity {top_alt.get('similarity_score', 0):.2f})",
                        gnn_support=gnn_features.get("hidden_dependency_count", 0) > 0,
                    )
                )

            # Air freight expedition for high-value / high-risk
            if revenue_exposure > 10000 or risk_score > 0.8:
                cost_premium = revenue_exposure * 0.15
                candidates.append(
                    self._make_candidate(
                        action_type="expedite_air_freight",
                        target_entity_id=entity_id,
                        parameters={"mode": "air", "priority": "express"},
                        predicted_nev=revenue_exposure * 0.85 - cost_premium,
                        predicted_sla_pct=0.95,
                        predicted_cost=cost_premium,
                        delay_reduction=max(3, current_delay_days * 0.7),
                        confidence=0.85,
                        explanation="Expedite via air freight to protect SLA — costly but fastest resolution",
                        gnn_support=gnn_features.get("critical_node_probability", 0) > 0.5,
                    )
                )

            # Split across suppliers
            if len(similar_suppliers) >= 2:
                candidates.append(
                    self._make_candidate(
                        action_type="split_order_across_suppliers",
                        target_entity_id=entity_id,
                        parameters={
                            "splits": [
                                {
                                    "supplier_id": s["supplier_id"],
                                    "percentage": round(1.0 / (len(similar_suppliers) + 1), 2),
                                }
                                for s in similar_suppliers[:2]
                            ]
                            + [
                                {
                                    "supplier_id": entity_id,
                                    "percentage": round(1.0 / (len(similar_suppliers) + 1), 2),
                                }
                            ],
                        },
                        predicted_nev=revenue_exposure * 0.6 - revenue_exposure * 0.06,
                        predicted_sla_pct=0.88,
                        predicted_cost=revenue_exposure * 0.06,
                        delay_reduction=current_delay_days * 0.3,
                        confidence=0.7,
                        explanation=f"Split order across {len(similar_suppliers[:2]) + 1} suppliers to diversify risk",
                        gnn_support=gnn_features.get("bottleneck_score", 0) > 0.4,
                    )
                )

        # Port / logistics risk
        if (
            "port" in entity_kind.lower()
            or "route" in entity_kind.lower()
            or blast_radius_count > 20
        ):
            candidates.append(
                self._make_candidate(
                    action_type="reroute_via_alternate_port",
                    target_entity_id=entity_id,
                    parameters={"reroute": True, "priority": "high"},
                    predicted_nev=revenue_exposure * 0.65 - revenue_exposure * 0.1,
                    predicted_sla_pct=0.82,
                    predicted_cost=revenue_exposure * 0.1,
                    delay_reduction=current_delay_days * 0.4,
                    confidence=0.65,
                    explanation="Reroute shipment via alternate port to bypass congestion",
                    gnn_support=gnn_features.get("bottleneck_score", 0) > 0.5,
                )
            )

        # Inventory-based
        if "product" in entity_kind.lower() or "inventory" in entity_kind.lower():
            candidates.append(
                self._make_candidate(
                    action_type="increase_safety_stock",
                    target_entity_id=entity_id,
                    parameters={"extra_units_pct": 0.2},
                    predicted_nev=revenue_exposure * 0.4 - revenue_exposure * 0.03,
                    predicted_sla_pct=0.8,
                    predicted_cost=revenue_exposure * 0.03,
                    delay_reduction=0,
                    confidence=0.6,
                    explanation="Temporarily increase safety stock by 20% as buffer",
                    gnn_support=False,
                )
            )

            candidates.append(
                self._make_candidate(
                    action_type="reallocate_inventory",
                    target_entity_id=entity_id,
                    parameters={"from_warehouses": ["nearest"], "priority": "demand-weighted"},
                    predicted_nev=revenue_exposure * 0.5,
                    predicted_sla_pct=0.85,
                    predicted_cost=revenue_exposure * 0.02,
                    delay_reduction=current_delay_days * 0.3,
                    confidence=0.7,
                    explanation="Reallocate inventory from non-priority warehouses",
                    gnn_support=False,
                )
            )

        # Always provide a "do nothing" / conservative baseline for comparison
        candidates.append(
            self._make_candidate(
                action_type="hold_order_consolidate",
                target_entity_id=entity_id,
                parameters={"action": "wait_and_consolidate", "review_hours": 24},
                predicted_nev=-revenue_exposure * 0.3,
                predicted_sla_pct=max(0.2, 1.0 - risk_score),
                predicted_cost=0.0,
                delay_reduction=0,
                confidence=0.9,
                source="baseline",
                explanation="Wait and consolidate with next batch — cheapest option but highest SLA risk",
                gnn_support=False,
                policy_safe=True,
            )
        )

        # Sort by predicted NEV, cap at MAX
        candidates.sort(key=lambda c: c.predicted_nev, reverse=True)
        return candidates[: self.MAX_CANDIDATES_PER_DECISION]

    def _make_candidate(
        self,
        *,
        action_type: str,
        target_entity_id: str,
        parameters: dict[str, Any],
        predicted_nev: float,
        predicted_sla_pct: float,
        predicted_cost: float,
        delay_reduction: float,
        confidence: float,
        explanation: str,
        gnn_support: bool = False,
        source: str = "rl",
        policy_safe: bool = True,
    ) -> CandidateAction:
        return CandidateAction(
            candidate_id=f"CAND-{uuid4().hex[:10]}",
            action_type=action_type,
            target_entity_id=target_entity_id,
            parameters=parameters,
            predicted_nev=predicted_nev,
            predicted_sla_pct=max(0, min(1, predicted_sla_pct)),
            predicted_cost=max(0, predicted_cost),
            predicted_delay_reduction_days=max(0, delay_reduction),
            confidence=max(0, min(1, confidence)),
            policy_safe=policy_safe and self._passes_policy_guard(action_type, parameters),
            gnn_support_score=0.5 + (0.2 if gnn_support else 0),
            source=source,
            explanation=explanation,
        )

    def _passes_policy_guard(self, action_type: str, parameters: dict[str, Any]) -> bool:
        """Basic policy guard; the full policy gate is applied downstream."""
        blocked = {"cancel_order_permanently", "delete_supplier", "auto_execute"}
        return action_type not in blocked and action_type in CANDIDATE_ACTION_TYPES

    def evaluate_candidates(
        self,
        candidates: list[CandidateAction],
        simulation_results: dict[str, dict[str, Any]] | None = None,
    ) -> list[dict[str, Any]]:
        """Rank candidates after simulation returns.

        The RL generator proposes; the Digital Twin validates; this
        produces a deterministic comparison the policy engine and human
        can review.
        """
        simulation_results = simulation_results or {}
        ranked = []
        for c in candidates:
            sim = simulation_results.get(c.candidate_id, {})
            # Prefer simulated metrics if available
            nev = sim.get("nev", c.predicted_nev)
            sla = sim.get("sla_pct", c.predicted_sla_pct)
            cost = sim.get("cost", c.predicted_cost)
            # Deterministic score
            score = (
                nev * self.NEV_WEIGHT + sla * self.SLA_WEIGHT * abs(nev) - cost * self.COST_WEIGHT
            )
            ranked.append(
                {
                    **c.to_dict(),
                    "simulated_nev": round(nev, 2),
                    "simulated_sla_pct": round(sla, 4),
                    "simulated_cost": round(cost, 2),
                    "composite_score": round(score, 2),
                    "is_optimal": False,  # Set after sorting
                }
            )
        ranked.sort(key=lambda r: r["composite_score"], reverse=True)
        if ranked:
            ranked[0]["is_optimal"] = True
        return ranked


# Alias for clarity
RLCandidateGenerator = CandidateGenerator

_singleton: CandidateGenerator | None = None


def get_candidate_generator() -> CandidateGenerator:
    global _singleton
    if _singleton is None:
        _singleton = CandidateGenerator()
    return _singleton


def reset_candidate_generator() -> None:
    global _singleton
    _singleton = None
