import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Responsible AI Policy | Cortex',
  description: 'Responsible AI Policy detailing principles, limitations, and human control requirements.',
};

export default function ResponsibleAIPage() {
  return (
    <main className="min-h-screen bg-[#0A0A0A] py-20 px-6">
      <div className="max-w-[1440px] mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12">
        <aside className="lg:col-span-3 hidden lg:block">
          <div className="sticky top-24">
            <h3 className="text-white font-mono text-sm uppercase tracking-wider mb-4 border-b border-[#262626] pb-2">Table of Contents</h3>
            <ul className="space-y-3 text-[#999999] text-sm">
              <li><a href="#grounded-evidence" className="hover:text-[#10B981] transition-colors">1. Grounded Evidence Principle</a></li>
              <li><a href="#authority-boundaries" className="hover:text-[#10B981] transition-colors">2. Authority Boundaries</a></li>
              <li><a href="#human-review" className="hover:text-[#10B981] transition-colors">3. Human Review Requirements</a></li>
              <li><a href="#limitations" className="hover:text-[#10B981] transition-colors">4. Limitations and Disclaimers</a></li>
              <li><a href="#monitoring" className="hover:text-[#10B981] transition-colors">5. Monitoring and Evaluation</a></li>
              <li><a href="#escalation" className="hover:text-[#10B981] transition-colors">6. Escalation Procedures</a></li>
              <li><a href="#bias" className="hover:text-[#10B981] transition-colors">7. Bias and Fairness</a></li>
              <li><a href="#transparency" className="hover:text-[#10B981] transition-colors">8. Transparency</a></li>
            </ul>
          </div>
        </aside>

        <div className="lg:col-span-8 max-w-[800px] prose prose-invert prose-p:text-[#E5E5E5] prose-headings:text-white prose-a:text-[#10B981]">
          <Link href="/legal" className="text-[#10B981] no-underline hover:underline font-mono text-sm uppercase tracking-wider mb-8 inline-block">← Back to Legal</Link>
          
          <h1 className="text-4xl font-semibold mb-4">Responsible AI Policy</h1>
          
          <div className="flex gap-4 mb-12 font-mono text-xs uppercase tracking-wider text-[#999999] border-b border-[#262626] pb-6">
            <span>Effective Date: August 16, 2026</span>
            <span>Last Updated: August 16, 2026</span>
            <span>Version: 1.0</span>
            <span>Owner: AI Governance Board</span>
          </div>

          <p className="text-[#E5E5E5] leading-relaxed mb-12">
            Cortex is committed to developing and deploying AI technologies safely, ethically, and securely. This Responsible AI Policy establishes the mandatory guidelines and principles governing the operation of AI components within the Cortex platform.
          </p>

          <section id="grounded-evidence" className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-white">1. Grounded Evidence Principle</h2>
            <p className="text-[#E5E5E5] leading-relaxed mb-4">
              All outputs and recommendations generated by the platform must be evaluated based on grounded evidence. The system is designed to present its analysis alongside the relevant underlying data context, enabling operators to independently verify the rationale before proceeding.
            </p>
          </section>

          <section id="authority-boundaries" className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-white">2. Authority Boundaries</h2>
            <p className="text-[#E5E5E5] leading-relaxed mb-4">
              Cortex systems strictly operate within predefined authority boundaries. Agents and analytical models cannot act autonomously. They do not possess the capability to execute state-changing actions in customer environments without explicit operator authorization. The platform functions as an advisory and orchestration layer, not an autonomous agent.
            </p>
          </section>

          <section id="human-review" className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-white">3. Human Review Requirements</h2>
            <p className="text-[#E5E5E5] leading-relaxed mb-4">
              We enforce a rigorous "Human-in-the-Loop" (HITL) architecture. Customers must ensure that qualified personnel review all platform outputs. Any execution or orchestration proposed by the system must be manually verified and approved by a human operator before taking effect.
            </p>
          </section>

          <section id="limitations" className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-white">4. Simulation Limitations and Disclaimers</h2>
            <p className="text-[#E5E5E5] leading-relaxed mb-4">
              Demonstrations, synthetic environments, and simulations provided by Cortex are controlled instances designed for evaluation purposes. They do not reflect live production environments. Outputs can be probabilistic and may occasionally contain inaccuracies. Users must evaluate all outputs critically rather than relying on them as definitive truth.
            </p>
          </section>

          <section id="monitoring" className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-white">5. Monitoring and Evaluation</h2>
            <p className="text-[#E5E5E5] leading-relaxed mb-4">
              Cortex continuously monitors platform telemetry to evaluate system performance, safety, and adherence to alignment protocols. We log authorization events and system recommendations to provide comprehensive audit trails, ensuring operational accountability.
            </p>
          </section>

          <section id="escalation" className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-white">6. Escalation Procedures</h2>
            <p className="text-[#E5E5E5] leading-relaxed mb-4">
              In the event that the platform generates harmful, severely inaccurate, or misaligned outputs, operators must halt the workflow immediately and report the incident via our designated escalation channels. The Cortex security and engineering teams will investigate and remediate the issue prior to resumption.
            </p>
          </section>

          <section id="bias" className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-white">7. Bias and Fairness</h2>
            <p className="text-[#E5E5E5] leading-relaxed mb-4">
              We are dedicated to mitigating unfair bias in platform outputs. Cortex regularly evaluates the underlying models and processing pipelines to identify and address systemic bias, ensuring the platform provides objective and equitable analyses across diverse datasets.
            </p>
          </section>

          <section id="transparency" className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-white">8. Transparency</h2>
            <p className="text-[#E5E5E5] leading-relaxed mb-4">
              Transparency is core to our design. Cortex strives to provide clear indicators of confidence levels, data sources, and the reasoning behind specific recommendations, empowering users to make informed decisions during the authorization process.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
