"""Nexus v0.7 — Persistence layer.

Replaces in-memory singletons with PostgreSQL-backed repositories.
"""

from app.modules.nexus_spine.persistence.models import (
    ApprovalRecordDB,
    DecisionRecordDB,
    DecisionTransitionDB,
    EventRecordDB,
    EvidenceEdgeDB,
    EvidenceNodeDB,
    ExecutionRecordDB,
    ForecastRecordDB,
    ModelRegistryEntryDB,
    ObservationRecordDB,
    OutcomeRecordDB,
    RecommendationRecordDB,
    RiskRecordDB,
    ScenarioRecordDB,
    VanessaMessageDB,
    VanessaSessionDB,
)
from app.modules.nexus_spine.persistence.repositories import (
    DecisionRepository,
    EventRepository,
    EvidenceRepository,
    ForecastRepository,
    ModelRegistryRepository,
    RecommendationRepository,
    RiskRepository,
    ScenarioRepository,
    VanessaSessionRepository,
    get_decision_repository,
    get_event_repository,
    get_evidence_repository,
    get_forecast_repository,
    get_model_registry_repository,
    get_recommendation_repository,
    get_risk_repository,
    get_scenario_repository,
    get_vanessa_session_repository,
    reset_repositories,
)

__all__ = [
    "ApprovalRecordDB",
    "DecisionRecordDB",
    "DecisionTransitionDB",
    "DecisionRepository",
    "EvidenceEdgeDB",
    "EvidenceNodeDB",
    "EvidenceRepository",
    "EventRecordDB",
    "EventRepository",
    "ExecutionRecordDB",
    "ForecastRecordDB",
    "ForecastRepository",
    "ModelRegistryEntryDB",
    "ModelRegistryRepository",
    "ObservationRecordDB",
    "OutcomeRecordDB",
    "RecommendationRecordDB",
    "RecommendationRepository",
    "RiskRecordDB",
    "RiskRepository",
    "ScenarioRecordDB",
    "ScenarioRepository",
    "VanessaMessageDB",
    "VanessaSessionDB",
    "VanessaSessionRepository",
    "get_decision_repository",
    "get_evidence_repository",
    "get_event_repository",
    "get_forecast_repository",
    "get_model_registry_repository",
    "get_recommendation_repository",
    "get_risk_repository",
    "get_scenario_repository",
    "get_vanessa_session_repository",
    "reset_repositories",
]
